// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaaxydqaiktwwztbfdwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhYXh5ZHFhaWt0d3d6dGJmZHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTU1NTUsImV4cCI6MjA1NjY3MTU1NX0.Bz-o78fbyX9qiyIdZzvPhG3WD7S1wfxq9tGG9r2hWxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);